# Generated by Django 2.2.9 on 2020-02-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attacks', '0001_initial'),
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damageDealt', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=5)),
                ('picked', models.BooleanField(default=False)),
                ('killed', models.BooleanField(default=False)),
                ('attacks', models.ManyToManyField(to='attacks.Attack')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding', to='monster.Monsta')),
            ],
        ),
    ]
