# Generated by Django 2.2.9 on 2020-02-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('bindings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding', to='players.Player'),
        ),
    ]
